// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8AJ-WmNqEQ0xY5pCXFpsdMiMDEMVJdRI',
    appId: '1:305329473005:web:085a922e3ad1a82d2793e4',
    messagingSenderId: '305329473005',
    projectId: 'chat-app-b2142',
    authDomain: 'chat-app-b2142.firebaseapp.com',
    storageBucket: 'chat-app-b2142.appspot.com',
    measurementId: 'G-HH62DV8V4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkmLTLShzx9TiAYExzK3318e_egp9t80U',
    appId: '1:305329473005:android:3bd8f2d80f521f9c2793e4',
    messagingSenderId: '305329473005',
    projectId: 'chat-app-b2142',
    storageBucket: 'chat-app-b2142.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCke_ndo0ZgfD9ari-l7qQhMTrJS4vcfhs',
    appId: '1:305329473005:ios:85bcb1baba363d7b2793e4',
    messagingSenderId: '305329473005',
    projectId: 'chat-app-b2142',
    storageBucket: 'chat-app-b2142.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCke_ndo0ZgfD9ari-l7qQhMTrJS4vcfhs',
    appId: '1:305329473005:ios:85bcb1baba363d7b2793e4',
    messagingSenderId: '305329473005',
    projectId: 'chat-app-b2142',
    storageBucket: 'chat-app-b2142.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8AJ-WmNqEQ0xY5pCXFpsdMiMDEMVJdRI',
    appId: '1:305329473005:web:97961c82b21c8a5d2793e4',
    messagingSenderId: '305329473005',
    projectId: 'chat-app-b2142',
    authDomain: 'chat-app-b2142.firebaseapp.com',
    storageBucket: 'chat-app-b2142.appspot.com',
    measurementId: 'G-W9XFJLJYMW',
  );
}
